"""Add DailyPuzzle model

Revision ID: 961a192d0911
Revises: 
Create Date: 2024-12-01 16:41:33.349187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '961a192d0911'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_puzzle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puzzle_date', sa.Date(), nullable=False),
    sa.Column('puzzle', sa.String(length=81), nullable=False),
    sa.Column('solution', sa.String(length=81), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('puzzle_date')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puzzle', sa.String(length=81), nullable=False),
    sa.Column('solution', sa.String(length=81), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_puzzles', schema=None) as batch_op:
        batch_op.drop_index('idx_daily_puzzles_date')

    op.drop_table('daily_puzzles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_puzzles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('puzzle_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('puzzle', sa.VARCHAR(length=81), autoincrement=False, nullable=False),
    sa.Column('solution', sa.VARCHAR(length=81), autoincrement=False, nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='daily_puzzles_pkey'),
    sa.UniqueConstraint('puzzle_date', name='daily_puzzles_puzzle_date_key')
    )
    with op.batch_alter_table('daily_puzzles', schema=None) as batch_op:
        batch_op.create_index('idx_daily_puzzles_date', ['puzzle_date'], unique=False)

    op.drop_table('game')
    op.drop_table('daily_puzzle')
    # ### end Alembic commands ###
